# CI NetBSD GitHub Actions workflow for monolith

name: CI (NetBSD)

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'assets/'
    - 'dist/'
    - 'snap/'
    - 'Dockerfile'
    - 'LICENSE'
    - 'Makefile'
    - 'monolith.nuspec'
    - 'README.md'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and test (netbsd)
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: Test in NetBSD
      uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        prepare: |
          /usr/sbin/pkg_add curl cwrappers gmake mktools pkgconf
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        run: |
          export PATH="/root/.cargo/bin:$PATH"
          cargo build --all --locked --verbose --no-default-features --features cli
          cargo test --all --locked --verbose --no-default-features --features cli
